# Generated by Django 2.2.7 on 2021-05-01 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_auto_20210501_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
